### PR TITLE
Group step pillow830 typeerror

### PR DESCRIPTION
**Pull request by fridex**
## Related issues or additional information of the supplied change

Related: https://github.com/thoth-station/adviser/issues/1969
Depends-On: https://github.com/thoth-station/adviser/pull/2156

## Description

Rewrite prescription to a new group step logic.

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... requires https://github.com/thoth-station/adviser/pull/2156

**Review by pacospace — APPROVED** [review]
lgtm!!

**Comment by fridex** [comment]
Merging manually, pipelines look lazy.

**Pull request merged**
