### PR TITLE
Fix PyPI artifact size prescriptions by listing all desired versions

### PR DESCRIPTION
**Pull request by fridex**
## Description

Related: https://github.com/thoth-station/prescriptions-refresh-job/pull/89/

Provide all versions in prescriptions that show PyPI artifact size. Also, apply solver rules for filtering out packages that versions are not monitored by Thoth's resolver.

### CODE REVIEW

**Comment by fridex** [comment]
It is starting to be fun:

```yaml
count:
  boots_count: 11266
  pseudonyms_count: 2
  sieves_count: 44
  steps_count: 23
  strides_count: 0
  wraps_count: 213073
count_all: 224408
prescriptions:
- name: thoth
```

Maybe we should add only those that have more than X MiB.

**Comment by fridex** [comment]
Adjusted to have only 3+MiB:

```yaml
count:
  boots_count: 11266
  pseudonyms_count: 2
  sieves_count: 44
  steps_count: 23
  strides_count: 0
  wraps_count: 88985
count_all: 100320
prescriptions:
- name: thoth
  release: dev+git
```

**Comment by fridex** [comment]
/unhold
/assign @mayaCostantini 

PTAL

**Comment by mayaCostantini** [comment]
lgtm
/approve

**Pull request merged**
