### PR TITLE
Fix issues in the schema

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- No

### CODE REVIEW

**Review by mayaCostantini — APPROVED** [review]
lgtm, thanks! 👍🏻 💯

**Comment by fridex** [comment]
> /retest

Checks might be too busy given the prescriptions update load.

**Comment by codificat** [comment]
> Checks might be too busy given the prescriptions update load.

The pre-commit check is running now. The queue was looking good, checked it before starting. Right now, this pre-commit check is the only one running.

Having said that, it's true that the pre-commit checks in the repo do take some time: right now the test has been running for over 12 minutes, just recently finishing `Check yaml` and currently running `yamllint`.

Is there room to fine tune the pre-commit configuration in this repo to make it more efficient?

**Comment by fridex** [comment]
Thanks for digging into this. 👍🏻 

I cannot think of any optimization. We have [allocated resources](https://github.com/thoth-station/prescriptions/pull/18628) - it definitely helped. The yamllling pre-commit checks take some time even when running locally given the repository size.

**Comment by codificat** [comment]
Ok, test completed now. This pre-commit job in particular started at 10:37 and finished at 11:19.

/approve

**Pull request merged**
