### PR TITLE
Warn if no CUDA was detected but tensorflow-gpu is installed

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
lgtm
one thing, i think tensorflow-gpu also work for cpu and it wont error out

**Comment by fridex** [comment]
> one thing, i think tensorflow-gpu also work for cpu and it wont error out

I think so (tensorflow-cpu is ~2x smaller though). What would be the best to recommend in this case? Should we adjust the recommendation message in some way? CC also @sub-mod

**Comment by sub-mod** [comment]
tensorflow-cpu  is not compiled with CUDA bit so it is smaller in size.
tensorlfow-gpu wheel is the same as tensorflow wheel and works for both CPU & GPU. 
If a smaller wheel size is desired while running on the CPU then it is recommended using tensorflow-cpu.

**Comment by fridex** [comment]
> tensorflow-cpu is not compiled with CUDA bit so it is smaller in size.
> tensorlfow-gpu wheel is the same as tensorflow wheel and works for both CPU & GPU.
> If a smaller wheel size is desired while running on the CPU then it is recommended using tensorflow-cpu.

Thanks, Subin for the clarification. Let's rephrase the message based on your suggestion then. 👍🏻

**Comment by fridex** [comment]
I will merge this not to have this stalled. Feel free to raise any comments/suggestions to eventually create a better solution. Thanks for the inputs everyone.

/approve

**Pull request merged**
